apiVersion: v2
name: occtet-curator
description: A Helm chart for Occtet Curator application - frontend and backend microservices
type: application
version: 0.0.1
appVersion: "0.0.1"
home: https://github.com/bitsea/occtet-curator
maintainers:
  - name: Bitsea
keywords:
  - occtet
  - curator
  - compliance
  - sbom
dependencies:
  - name: postgres
    version: "0.20.4"
    repository: "oci://registry-1.docker.io/cloudpirates"
    condition: postgresql.enabled
    alias: postgresql
  - name: nfs-server-provisioner
    version: "1.8.0"
    repository: "https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/"
    condition: nfsprovisioner.enabled
    alias: nfsprovisioner

